document.write('<div class="nav_bar">');
document.write('    <div class="nav_logo">');
document.write('        <a href="http://web.mit.edu/laserson/www/">');
document.write('            <img src="images/UriLogo.svg">');
document.write('        </a>');
document.write('    </div>');
document.write('    <div class="nav_col">');
document.write('        <a href="http://web.mit.edu/laserson/www/software.html">PROJECTS</a> <br />');
document.write('        <a href="http://web.mit.edu/laserson/www/stuff.html">BLOG</a>');
document.write('    </div>');
document.write('    <div class="nav_col">');
document.write('        <a href="http://web.mit.edu/laserson/www/stuff.html">RESEARCH</a> <br />');
document.write('        <a href="http://web.mit.edu/laserson/www/stuff.html">CV</a>');
document.write('    </div>');
document.write('    <div class="nav_col">');
document.write('        <a href="http://web.mit.edu/laserson/www/stuff.html">HOME</a> <br />');
document.write('        <a href="http://web.mit.edu/laserson/www/stuff.html">PERSONAL</a>');
document.write('    </div>');
document.write('</div>');
