document.write('<div class="nav_bar">');
document.write('    <div class="nav_logo">');
document.write('        <a href="http://web.mit.edu/laserson/www/">');
document.write('            <img src="images/UriLogo.svg" id="logo">');
document.write('        </a>');
document.write('    </div>');
document.write('    <div class="nav_col">');
document.write('        <a href="http://web.mit.edu/laserson/www/coming_soon.html">PROJECTS</a> <br />');
document.write('        <a href="http://web.mit.edu/laserson/www/coming_soon.html">BLOG</a>');
document.write('    </div>');
document.write('    <div class="nav_col">');
document.write('        <a href="http://web.mit.edu/laserson/www/coming_soon.html">RESEARCH</a> <br />');
document.write('        <a href="http://web.mit.edu/laserson/www/docs/resume20111205.pdf">CV</a>');
document.write('    </div>');
document.write('    <div class="nav_col">');
document.write('        <a href="http://web.mit.edu/laserson/www/">HOME</a> <br />');
document.write('        <a href="http://web.mit.edu/laserson/www/coming_soon.html">PERSONAL</a>');
document.write('    </div>');
document.write('</div>');
