document.write('<div class="nav_bar">');
document.write('    <div class="nav_logo">');
document.write('        <a href="http://web.mit.edu/laserson/www/">');
document.write('            <img src="images/UriLogo.svg">');
document.write('        </a>');
document.write('    </div>');
document.write('    <div class="nav_elt">');
document.write('        <a href="http://web.mit.edu/laserson/www/about.html">ABOUT</a>');
document.write('    </div>');
document.write('    <div class="nav_elt">');
document.write('        <a href="http://web.mit.edu/laserson/www/research.html">RESEARCH</a>');
document.write('    </div>');
document.write('    <div class="nav_elt">');
document.write('        <a href="http://web.mit.edu/laserson/www/software.html">SOFTWARE</a>');
document.write('    </div>');
document.write('    <div class="nav_elt">');
document.write('        BLOG');
document.write('    </div>');
document.write('    <div class="nav_elt">');
document.write('        <a href="http://web.mit.edu/laserson/www/stuff.html">STUFF</a>');
document.write('    </div>');
document.write('</div>');
